### ISSUE TITLE
Release 1.2.1 with mix.lock?

### ISSUE THREAD

**Issue by agamdua** [KamilLelonek/yaml-elixir#10]
At the moment I have to add `{ :yamerl, "~> 0.3.2"}` to the `deps` block in my `mix.exs`.

It seems like #9 fixes this. 

I am new to Elixir though, so if there is a different way to do these things, please excuse my ignorance.

**Comment by KamilLelonek** [comment]
Done. Can you check that?

**Comment by mthadley** [comment]
Just ran into this issue, I initially started with version `1.1.0` since it was the only git tag I saw here. However the I saw this issue and the version on hex and used `1.2.1` instead. It seems to have fixed it! Thanks!
