### ISSUE TITLE
API throws errors, not return {:ok, result}|{:error, error} tuple.

### ISSUE THREAD

**Issue by Virviil** [KamilLelonek/yaml-elixir#11]
Issue in the header, i think it's not so comfortable.

**Comment by KamilLelonek** [comment]
In what case?

**Comment by Virviil** [comment]
In each case when you want to handle error. For example, if file not exist, or if you want to make custom yaml-parsing errors handling. I'll try too make the PR, with read and read! functions to handle functionality
