### ISSUE TITLE
YamlElixir.read_from_string throws error from yamerl

### ISSUE THREAD

**Issue by superchris** [KamilLelonek/yaml-elixir#12]
iex(2)> story = "\*\*foo\*\*"
"\*\*foo\*\*"
iex(3)> YamlElixir.read_from_string story
** (MatchError) no match of right hand side value: :undefined
         (yamerl) src/yamerl_app.erl:67: :yamerl_app.get_param/1
         (yamerl) src/yamerl_constr.erl:450: :yamerl_constr.setup_node_mods/1
         (yamerl) src/yamerl_constr.erl:520: :yamerl_constr.initialize/1
         (yamerl) src/yamerl_constr.erl:203: :yamerl_constr.string/2
    (yaml_elixir) lib/yaml_elixir.ex:15: YamlElixir.read_from_string/1

**Comment by superchris** [comment]
Forget it was using old version

**Comment by bobbypriambodo** [comment]
I'm getting this error too, I'm on `yaml_elixir@1.2.1`. @superchris which version are you using?
