### ISSUE TITLE
Can't compile yamerl

### ISSUE THREAD

**Issue by seadynamic8** [KamilLelonek/yaml-elixir#13]
Getting this when try to compile yaml-elixir:

```
** (Mix) Could not compile dependency :yamerl, "escript.exe "[home_dir]/.mix/rebar3" bare compile --paths "[project_dir]/_build/dev/lib/*/ebin"" command failed.
```

This is on Windows 10.  I'm using escripts as well.

Any ideas what could be wrong?

**Comment by KamilLelonek** [comment]
Hey, have you looked at https://github.com/elixir-lang/elixir/issues/3857?

**Comment by seadynamic8** [comment]
Nope, I haven't.  Sorry, I've decided to go with just Mix config since it fits my problem.  Will close issue for now.
