### ISSUE TITLE
Untrusted DoS vuln in yamerl

### ISSUE THREAD

**Issue by skull-squadron** [KamilLelonek/yaml-elixir#18]
Reported here: https://github.com/yakaz/yamerl/issues/18

**Comment by KamilLelonek** [comment]
What do you suggest as a solution @steakknife?

**Comment by skull-squadron** [comment]
WIP: In contact with maintainer and will report back because it needs an
urgent bug-fix. No ETA yet but I'll be troubleshooting on this tomorrow
daytime too.

**Comment by skull-squadron** [comment]
This has been solved by the maintainer in 0.5.0.

**Comment by kyleaa** [comment]
@KamilLelonek could we get a yaml-elixir release that requires 0.5.0 to resolve this issue? I've overridden the yamerl dep in my project for now, but theres some other fixes in master here that would be nice to also have in hex.

**Comment by KamilLelonek** [comment]
Would you create Pull Request to fix that?
