### ISSUE TITLE
I'm wondering why this is an application?

### ISSUE THREAD

**Issue by pragdave** [KamilLelonek/yaml-elixir#21]
As far as I can see it has no state, and no servers.

Couldn't it just be a simple library?

Cheers

Dave

**Comment by KamilLelonek** [comment]
Yes it can! Can you prepare PR for that?

**Comment by pragdave** [comment]
Normally I'd love to, but I just don't have time to spare right now.

**Comment by KamilLelonek** [comment]
I'm closing the issue then.

**Comment by samb1729** [comment]
This issue isn't resolved, so I think it should be reopened. I'm willing to tackle the change.

**Comment by KamilLelonek** [comment]
@sambooo if you are gonna change that, then please reopen this issue and go ahead.

**Comment by samb1729** [comment]
I'm unable to reopen the issue as I'm not the owner of this repo. I could file a duplicate issue but that just fragments the conversation. Could you please click the button?
