### ISSUE TITLE
Misleading error when yamerl is not running

### ISSUE THREAD

**Issue by samb1729** [KamilLelonek/yaml-elixir#25]
When yamerl is not running, calling a function such as `YamlElixir.read_all_from_file("foo.yaml")` incorrectly returns `{:error, "malformed yaml"}` because the changes in #24 assume all exceptions raised are due to malformed yaml.

These functions should instead check whether yamerl is running, and provide a more useful error if it isn't.

**Comment by KamilLelonek** [comment]
Fixed in [`2.0.2`](https://hex.pm/packages/yaml_elixir/2.0.2).
