### ISSUE TITLE
Have you considered returning keyword lists instead of maps?

### ISSUE THREAD

**Issue by bzitzow** [KamilLelonek/yaml-elixir#32]
First of all, thanks for your work!

I realize the risks regarding atom over use, and I wouldn't suggest this as a default, however, with a small configuration file, I was hoping I could get the data in this syntax.

Cheers!

Example YAML:
```yaml
service_two:
  - name: Service Two
  - service_group: GROUP
  - host: HOSTNAME
  - port: 
```

Currently Returns:
```elixir
%{
   "service_two" => [
     %{"name" => "Service Two"},
     %{"service_group" => "GROUP"},
     %{"host" => "HOSTNAME"},
     %{"port" => nil}
   ]
 }
```

Would like the option to return:
```elixir
%{
   "service_two" => [
     name: "Service Two",
     service_group: "GROUP",
     host: "HOSTNAME",
     port: nil
   ]
 }
```

**Comment by KamilLelonek** [comment]
You can prepare a pull request, I'm open for changes like that!

**Comment by msimonborg** [comment]
This doesn't work as intended da9cdf3c9178d6b5da774eb4d8b828b6d44d7c66

The test passes because it never executes an assertion:

```
test "sigil list atom" do
    import YamlElixir.Sigil
    yaml = ~y"""
    ---
    list:
      - a: 1
      - b: 2
      - c: 3
      - d: 4
    """a

    %{"list" => [a: 1, b: 2, c: 1, d: 4]} == yaml
  end
```

The last line evaluates to false but it's ignored without the `assert` macro and the test always passes. There's a warning when running the test:

```
$ mix test
warning: use of operator == has no effect
  test/yaml_elixir_test.exs:162
```

The actual return value of the function is a list of maps with string keys:

```
%{"list" => [%{"a" => 1}, %{"b" => 2}, %{"c" => 3}, %{"d" => 4}]}
```

**Comment by KamilLelonek** [comment]
@msimonborg thank's for spotting that. Please prepare your suggested changes as Pull Request, I'll review them.

**Comment by msimonborg** [comment]
I would but I'm not totally clear how it's actually supposed to work without any API documentation to reference and the test case seems to go against the readme example.

If it's supposed to return atoms then shouldn't the `sigil_y/2` call in the test case be:

```
yaml = ~y"""
    ---
    list:
      - :a: 1
      - :b: 2
      - :c: 3
      - :d: 4
    """a
```
?

**Comment by msimonborg** [comment]
I think this issue should be reopened, or we should open a new one. As far as I can tell the code introduced by commit da9cdf3 doesn't do what it's supposed to, and the test case to validate is broken.

I think the code may actually be doing nothing at all, b/c when you fix the test assertion you get the same results when the code is just reverted to the way it was before the commit.

I would suggest a fix, but I don't understand the intentions. Is it converted to a Keyword list even when you don't use the colon syntax for atoms that's used elsewhere? Or if you have a list of KVs then it's just implied that they keys should be atoms? And forming your YAML in this way:

```
list:
  - a: 1
  - b: 2
  - c: 3
  - d: 4
```
is sort of anti-idiomatic, isn't it? Wouldn't the following be better?
```
list:
  a: 1
  b: 2
  c: 3
  d: 4
```
If you don't want to reopen this issue so we can get clarification on the intended API and someone can propose a fix then I will open a pull request that just reverts the changes introduced by the commit

**Comment by KamilLelonek** [comment]
Please open a pull request to solve the issue you spotted.
