### ISSUE TITLE
Tag latest 2.1.0 version

### ISSUE THREAD

**Issue by lobo-tuerto** [KamilLelonek/yaml-elixir#34]
Would be good to have the latest version tagged.

This can help people see which is the latest version released using GitHub tags explorer, instead to have to dive into `mix.exs`.

**Comment by KamilLelonek** [comment]
Done in: https://github.com/KamilLelonek/yaml-elixir/tree/v2.1.0

**Comment by lobo-tuerto** [comment]
Weird, it wasn't showing them all before, just v1.1.
¯\_(ツ)_/¯

Thx

**Comment by lobo-tuerto** [comment]
Evidence.
![yaml-elixir-1](https://user-images.githubusercontent.com/5730/49491818-47f76080-f81b-11e8-97af-c0e6f29b5458.png)
