### ISSUE TITLE
More descriptive errors

### ISSUE THREAD

**Issue by msimonborg** [KamilLelonek/yaml-elixir#35]
Currently it appears that any error thrown from yamerl when calling a non-bang function is caught and returned as `{:error, "malformed yaml"}`. This is the case even for errors like file not found, which is misleading. For example if you attempt to read from a non-existent file yamerl will throw:

```elixir
[{:yamerl_parsing_error, :error, message, :undefined, :undefined, :file_open_failure, :undefined, [error: :enoent]}]}
```
where `message` will be something like `'Failed to open file "path/to/non-existent/file.yml": no such file or directory'`

It seems like the error messages that YamlElixir provides should be more accurate than "malformed yaml", particularly since yamerl is providing useful information such as the reason and a message about the bad path.

Also, it would be nice if the bang functions raised a helpful Elixir exception (`YamlElixir.FileNotFoundError` perhaps?) rather than just allowing the error from yamerl to be thrown.

Thanks for the great library! I appreciate the work

**Comment by KamilLelonek** [comment]
I agree this will be a very good improvement.

Any Pull Request from your side is appreciated. I'll review it with
pleasure.

Thank you for your input.

**Comment by msimonborg** [comment]
I'm a little short on availability but I may be able to find time to work on a PR soon. Maybe this weekend.

Thanks!

**Comment by msimonborg** [comment]
@KamilLelonek There are two ways I can think of that this could be done for non-bang functions.

1.  `{:error, "Failed to open file \"path/to/non-existent/file.yml\": no such file or directory"}`
2. `{:error, %YamlElixir.FileNotFoundError{message: "Failed to open file \"path/to/non-existent/file.yml\": no such file or directory"}}`

I like the second pattern because a developer can pattern match on the exception and decide for themselves whether to raise it, extract the message from it, or something else.

Do you have a preference?

**Comment by KamilLelonek** [comment]
I agree with you. Having a domain error will allow users to better pattern-match on it.
