### ISSUE TITLE
Publish 2.3.1 or 2.4 ?

### ISSUE THREAD

**Issue by DianaOlympos** [KamilLelonek/yaml-elixir#40]
Hello,

It seems there were some code warnings in 2.3. that got cleaned up with [this commit](https://github.com/KamilLelonek/yaml-elixir/commit/688b03992552abc8a306e0d0cfb35efb94743bcc).

Would it be possible to push a version to hex that has these ? It would be nice to avoid some possible errors.

Thanks

**Comment by KamilLelonek** [comment]
Done!
