### ISSUE TITLE
Using "<<: *link" syntax does no produce expected result

### ISSUE THREAD

**Issue by dolfinus** [KamilLelonek/yaml-elixir#44]
Hi.

I've faced with an issue with substitution one map keys an values into another one.

This syntax works correctly:
```elixir
yaml = """
  me: &link
    name: a
    id: 1
  other: *link
"""
# "me: &link\n  name: a\n  id: 1\nother: *link\n"
YamlElixir.read_from_string(yaml)
#{:ok, %{"me" => %{"id" => 1, "name" => "a"}, "other" => %{"id" => 1, "name" => "a"}}}
```

But this is not:
```elixir
yaml = """
  me: &link
    name: a
    id: 1
  other:
    <<: *link
    id: 2
"""
# "me: &link\n  name: a\n  id: 1\nother:\n  <<: *link\n  id: 2\n"

YamlElixir.read_from_string(yaml)
# {:ok,
#  %{
#    "me" => %{"id" => 1, "name" => "a"},
#    "other" => %{"<<" => %{"id" => 1, "name" => "a"}, "id" => 2}
#  }}
```
The expected result is substituting all key-values from `*link` into the second map. These keys can be update with new values, like `id` field in this example.
But instead it produces a nested map with "<<" key, and map merging does not work as expected.

This syntax is a part of YAML 1.1 standart:
https://yaml.org/type/merge.html
and is supported by a lot of libraries for other languages, such as Ruby (YAML module) and Python (pyyaml).

Could you please fix this behavior?

**Comment by KamilLelonek** [comment]
Hey, thanks for reporting this. Feel free to open a PR with this feature :)
