### ISSUE TITLE
Add docs

### ISSUE THREAD

**Issue by janpieper** [KamilLelonek/yaml-elixir#59]
At some point I was a bit confused why `YamlElixir.read_all_from_string!/1` returns me a list when reading a single file until I remembered that you can have multiple documents within a single YAML file.

So I need to use `YamlElixir.read_from_string!/1` when I only expect a single document in a file:

```elixir
iex> YamlElixir.read_from_string!("""
...> foo:
...>   bar: 1
...> """)
%{"foo" => %{"bar" => 1}}
```

And `YamlElixir.read_all_from_string!/1` when I expect the file to contain one or more documents.

```elixir
iex> YamlElixir.read_all_from_string!("""
...> foo:
...>   bar: 1
...> ---
...> foo:
...>   bar: 2
...> """)
[%{"foo" => %{"bar" => 1}}, %{"foo" => %{"bar" => 2}}]
```

It would be great to have some `@doc` and `@moduledoc` in the code, because currently the rendered docs are not really helpful.

See: https://hexdocs.pm/yaml_elixir/YamlElixir.html

![Screenshot from 2023-09-11 11-55-02](https://github.com/KamilLelonek/yaml-elixir/assets/426371/76b5e6de-4bd7-4ffb-9ce9-26d1517bfb7f)

**Comment by KamilLelonek** [comment]
Sure! Please create a pull request.
