### ISSUE TITLE
Update hex.pm package

### ISSUE THREAD

**Issue by lucidstack** [KamilLelonek/yaml-elixir#6]
Hey there,

I've just noticed that hex.pm has only got version `1.0.0` of this package, and it's pretty confusing at the moment because of features not in line with the README on here. Would it be possible to push version `1.1.0` to hex?

Thank you for making this by the way! :grinning:

**Comment by KamilLelonek** [comment]
Should be up to date: https://hex.pm/packages/yaml_elixir
